//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TVshow
    {
        public int ShowID { get; set; }
        public string Showname { get; set; }
        public string Genre { get; set; }
        public Nullable<int> SeasonNum { get; set; }
        public Nullable<int> ReleaseDate { get; set; }
    }
}
